### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by bucaran** [bucaran/fish-getopts#7]
![fish-getopts](https://cloud.githubusercontent.com/assets/8317250/12116592/33e728be-b3fe-11e5-9a1b-9314d08f2a26.png)

**Comment by bucaran** [comment]
![shell-getopts](https://cloud.githubusercontent.com/assets/8317250/12135658/ab6ddcec-b481-11e5-9323-7662f2ab2a55.png)
![shell-getopts-blue](https://cloud.githubusercontent.com/assets/8317250/12135660/af8fb232-b481-11e5-91e1-f2ed49f74527.png)
![shell-getopts-green](https://cloud.githubusercontent.com/assets/8317250/12135661/afb0988a-b481-11e5-9cbd-6a06afcadcd8.png)

**Comment by b4b4r07** [comment]
:+1:
